### ISSUE TITLE
Feature Request: allow formatted dictionary/list output in CLI

### ISSUE THREAD

**Issue by jonbees-ibm** [dod-cyber-crime-center/DC3-MWCP#33]
This issue cropped up when comparing the output of an alternative Cobalt Strike beacon parsing tool to that of an MWCP parser implementation. 
The alternative tool outputs dictionaries like this: 
```
HttpGet_Metadata                 - ConstHeaders
                                        Host: example.com
                                        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
                                        Accept-Language: en-US,en;q=0.5
                                 ...
```

When an Other metadata object with the same data is added to a report, the MWCP CLI output looks like this:
```
Tags    Key                Value
------  -----------------  --------------------------------------------------------------------------------
        httpget_metadata   {'ConstHeaders': ['Host: example.com', 'Accept: text/html,application/xhtml+
                             xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language: en-US,en;q=0.5'] ... }
```
Having to condense all of the keys and values into a single string and printing it out like any other string is not ideal for human-readability. 
If we could either implement support for printing list/dict items on different lines with visual nesting like the alternative tool I included an excerpt from or just use pprint on those objects before writing them to the CLI output, that would significantly improve the usability of the output for any parser which has objects it needs to output containing a set of keys that are not known beforehand.

**Comment by dc3-tsd** [comment]
Closing this issue due to age and inactivity.
