### ISSUE TITLE
Scheduled Task Metadata Field

### ISSUE THREAD

**Issue by ddash-ct** [dod-cyber-crime-center/DC3-MWCP#38]
Requesting the following addition to the standard metadata fields, due to prominence for persistence (scheduled tasks)

[Scheduled Tasks](https://learn.microsoft.com/en-us/windows/win32/taskschd/schtasks) are a common method for persistence on a Windows system, and it would be desirable to have standard metadata for its reporting, particularly to link task names with at least `taskrun` (can be a `metadata.Command`) parameters.

Would request at least the following parameters (reflected in the options from MSDN above), where most are optional:
* `taskname` (perhaps just as `name`
* `taskrun` (would be a `metadata.Command` - perhaps evaluate for filepaths?)
* `description`
* `author`

**Comment by dc3-tsd** [comment]
We added a `ScheduledTask` metadata element in the most recent release.  Please let us know if this will work for you.
