### ISSUE TITLE
Recursion Bug

### ISSUE THREAD

**Issue by ddash-ct** [dod-cyber-crime-center/DC3-MWCP#40]
Discovered an edge-case bug while attempting to use the YARA recursion feature. If one of the parsers for a sub-component dispatches a new file with a parent of it's sibling, it may not get picked up because the parent was already processed.

**Comment by DOCTYPEmike** [comment]
No bugs just make sure when you steal shit that you don't own ilike my fucking laptop and try to murder me be lucky I have my son that's all I love understand I know my system and how it works I'm not stupid or uneducated I stand for the brothers that died for our country i will be a fathers rights advocate and just man we are only people but im on the governments side and the cops side i have been my whole life god bless the USA
